Applications/MVC/Controllers/CLIController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCToyRobotChallenge.Models;
using MVCToyRobotChallenge.Services;
using System.Linq;
using System.Threading.Tasks;
using ToyRobotChallenge.Library.AppSupport.Application.Implementations.ExtraRobotCommands;
using ToyRobotChallenge.Library.AppSupport.Application.MediatR.Requests;
using ToyRobotChallenge.Library.AppSupport.Geometry;
using ToyRobotChallenge.Library.AppSupport.UserCommands;
using static ToyRobotChallenge.Library.Simulator;

namespace MVCToyRobotChallenge.Controllers
{
    public partial class CLIController
        : ToyRobotController
    {
        private readonly ILogger<CLIController> _logger;
        private readonly ICommandHistory _commandHistory;

        public CLIController(IMediator mediatR, ICommandHistory commandHistory, ILogger<CLIController> logger)
            : base(mediatR)
        {
            _logger = logger;
            _commandHistory = commandHistory;
        }
    }

    /// <summary>
    /// Endpoints
    /// </summary>
    public partial class CLIController
    { 
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await this._mediatR.Send(new Start((ulong)_tableHeight, (ulong)_tableWidth));

            // return model
            return View(await CreateCLIModelAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(ConsoleCLIModel input)
        {
            var command = input.CommandBuffer;

            // add command to command history
            this._commandHistory.Push(command);

            await ExecuteRobotCommandAsync(command);

            ModelState.Clear();

            return View(await CreateCLIModelAsync());
        }
    }

    /// <summary>
    /// Support
    /// </summary>
    public partial class CLIController
    { 
        private async Task ExecuteRobotCommandAsync(string command)
        {
            var commandList = new CommandList(command ?? string.Empty, true);

            if (commandList.Count() > 0)
            {
                foreach(var cmd in commandList)
                {
                    // commands handled at the application level
                    if(cmd is QuitCommand)
                    {
                        await ExecuteSimulationQuitAsync();
                    }
                    else if (cmd is HelpCommand)
                    {
                        await ExecuteDisplayHelpTextAsync();
                    }
                    else if(cmd is ReportCommand)
                    {
                        await ExecuteDisplayRobotReportAsync();
                    }
                    else
                    {
                        // command handled else where
                        await this._mediatR.Send(new Execute(cmd));
                    }
                }
            }
            else
            {
                // can't parse command in to command list. display a helpful hint
                this._commandHistory.Push("type h <enter> to display help, type q <enter> to reset the simulation");
            }
        }

        private async Task ExecuteSimulationQuitAsync()
        {
            await this._mediatR.Send(new Reset((ulong)_tableHeight, (ulong)_tableWidth));
        }

        private async Task ExecuteDisplayRobotReportAsync()
        {
            var robot = await this._mediatR.Send(new Execute(new ReportCommand()));

            if ((robot?.Vector?.IsRobotPlaced() ?? false) == false)
            {
                this._commandHistory.Push("Robot MUST be placed first!");
            }
            else
            {
                this._commandHistory.Push($"Position: ({robot.Vector.Position.X}, {robot.Vector.Position.Y}) Direction: {robot.Vector.Dir}");
            }
        }

        private Task ExecuteDisplayHelpTextAsync()
        {
            var lines = new string[]
            {
                "Use the following commands to ready & control your robot (commands are case insensitive!):",
                "PLACE [x],[y], [FACING]\" - Place the robot in the required x,y position in the required direction.",
                $"x,y are the grid coordinates 0 -> {this._tableWidth - 1} for width & 0->{this._tableHeight - 1} for height.",
                "    Facing is one of NORTH, EAST, SOUTH, WEST",
                "You must place your robot first, any other interactive commands will be ignored until the robot has been placed.",
                "You may place your robot as many tmes as you like.",
                "MOVE - Move the robot by 1 grid square in the direction it is facing.",
                "LEFT - Rotate the robot 90 degrees left in the current grid position.",
                "RIGHT - Rotate the robot 90 degrees right in the current grid position.",
                "REPORT - Display the robots current position & direction.",
                "WAVE - Give a little wave :-)",
                "JUMP - Give a little jump :-P"
            };

            this._commandHistory.Push(lines);

            return Task.CompletedTask;
        }

        private async Task<CLIModel> CreateCLIModelAsync()
        {
            var robot = await this._mediatR.Send(new Execute(new ReportCommand()));
            var robotModel = robot is null
                                ? null
                                : new ToyRobotModel(robot);

            var tableTop = new TabletopModel()
            {
                Rows = _tableHeight,
                Columns = _tableWidth,
                RobotModel = robotModel,
            };

            var console = new ConsoleCLIModel()
            {
                Commands = this._commandHistory.Commands,
                CommandBuffer = string.Empty,
            };

            var model = new CLIModel()
            {
                TabletopModel = tableTop,
                ConsoleModel = console,
            };

            return model;
        }
    }
}

Applications/MVC/Controllers/WASDController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCToyRobotChallenge.Models;
using System.Threading.Tasks;
using ToyRobotChallenge.Library.AppSupport.Application.MediatR.Requests;
using ToyRobotChallenge.Library.AppSupport.Geometry;
using ToyRobotChallenge.Library.Geometry;
using static ToyRobotChallenge.Library.Simulator;


namespace MVCToyRobotChallenge.Controllers
{
    public partial class WASDController
        : ToyRobotController
    {
        private readonly ILogger<WASDController> _logger;

        public WASDController(IMediator mediatR, ILogger<WASDController> logger)
            : base(mediatR)
        {
            _logger = logger;
        }
    }

    /// <summary>
    /// Endpoints
    /// </summary>
    public partial class WASDController
    {
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await this._mediatR.Send(new Start((ulong)_tableHeight, (ulong)_tableWidth));

            // return model
            return View(await CreateWASDModelAsync());
        }

        [ActionName("TurnLeft")]
        public async Task<IActionResult> TurnLeft()
        {
            await this._mediatR.Send(new Execute(new LeftTurnCommand()));

            // return model
            return View("Index", await CreateWASDModelAsync());
        }

        [ActionName("TurnRight")]
        public async Task<IActionResult> TurnRight()
        {
            await this._mediatR.Send(new Execute(new RightTurnCommand()));

            // return model
            return View("Index", await CreateWASDModelAsync());
        }

        [ActionName("Move")]
        public async Task<IActionResult> Move()
        {
            await this._mediatR.Send(new Execute(new MoveCommand()));

            // return model
            return View("Index", await CreateWASDModelAsync());
        }

        [ActionName("Reset")]
        public async Task<IActionResult> Reset()
        {
            await this._mediatR.Send(new Reset((ulong)_tableHeight, (ulong)_tableWidth));

            // return model
            return View("Index", await CreateWASDModelAsync());
        }

        [ActionName("Place")]
        public async Task<IActionResult> Place(ConsoleWASDModel model)
        {
            model.RobotModel.Vector.Dir = System.Enum.TryParse<Direction>(model.Direction, out var d) == true
                                            ? d
                                            : Direction.North;

            await this._mediatR.Send(new Execute(new PlaceCommand(model.RobotModel.Vector.ToULong())));

            // return model
            return View("Index", await CreateWASDModelAsync());
        }
    }

    /// <summary>
    /// Support
    /// </summary>
    public partial class WASDController
    { 
        private async Task<WASDModel> CreateWASDModelAsync()
        {
            var robot = await this._mediatR.Send(new Execute(new ReportCommand()));
            var robotModel = robot is null
                                ? null
                                : new ToyRobotModel(robot);

            var tableTop = new TabletopModel()
            {
                Rows = _tableHeight,
                Columns = _tableWidth,
                RobotModel = robotModel,
            };
           
            var console = new ConsoleWASDModel()
            {
                RobotModel = robotModel,
            };

            var model = new WASDModel()
            {
                TabletopModel = tableTop,
                ConsoleModel = console,
            };

            return model;
        }
    }
}

Applications/MVC/Views/Shared/_ConsoleCLI.cshtml
@model ConsoleCLIModel

<div class="container commandConsole">
    <div class="row commandHistory">
        <div class="col">
            @foreach (var command in this.Model.Commands)
            {
                @command<br>
            }
        </div>
    </div>

    @using (Html.BeginForm("Index", "CLI", FormMethod.Post))
    {
        <div class="row commandInput">
            <div class="col">
                <span class="commandPrompt">@this.Model.CommandPrompt</span>@Html.TextBoxFor(m => m.CommandBuffer, new { @id = "commandInputLineField" })
            </div>
        </div>
    }
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(function () {
        $('#commandInputLineField').focus();
    });
</script>
@{
}

Applications/MVC/Views/Shared/_ConsolePlace.cshtml
@using ToyRobotChallenge.Library.Geometry 
@model ConsoleWASDModel

<div class="container commandConsole">
    @using (Html.BeginForm("Place", "WASD", FormMethod.Post))
    { 
        <div class="row">
            <div class="col"></div>
            <div class="col"><h5>PLACE:</h5></div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"><span class="label">X: </span></div>
            <div class="col">@Html.TextBoxFor(m => m.RobotModel.Vector.Position.X, new { @class = "field" })</div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"><span class="label">Y: </span></div>
            <div class="col">@Html.TextBoxFor(m => m.RobotModel.Vector.Position.Y, new { @class = "field" })</div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"><span class="label">Direction: </span></div>
            <div class="col">
                <select class="field" name="@Html.NameFor(m => m.Direction)">
                    <option value="" disabled selected>Select your option</option>
                    <option value=@Direction.North>@Direction.North</option>
                    <option value=@Direction.East>@Direction.East</option>
                    <option value=@Direction.South>@Direction.South</option>
                    <option value=@Direction.West>@Direction.West</option>
                </select>
            </div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col"><button class="btn btn-primary btn-play" type="submit"><i class="fas fa-play"></i></button></div>
            <div class="col"></div>
        </div>
    }
</div>

@{
}

Applications/MVC/Views/Shared/_ConsoleWASD.cshtml
@model ConsoleWASDModel

<div class="container commandConsole">
    <div class="row">
        <div class="col"></div>
        <div class="col"><button class="btn btn-primary btn-play" value="Create" onclick="location.href='@Url.Action("TurnLeft",  "WASD")'"><i class="fas fa-caret-left"></i></button></div>
        <div class="col"><button class="btn btn-primary btn-play" value="Create" onclick="location.href='@Url.Action("Move",      "WASD")'"><i class="fas fa-caret-up"></i></button></div>
        <div class="col"><button class="btn btn-primary btn-play" value="Create" onclick="location.href='@Url.Action("TurnRight", "WASD")'"><i class="fas fa-caret-right"></i></button></div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col"><button class="btn btn-danger btn-reset" value="Create" onclick="location.href='@Url.Action("Reset", "WASD")'"><i class="fas fa-power-off"></i></button></div>
    </div> 
</div>

@{
}

Applications/MVC/Views/Shared/_Layout.cshtml
@inject SemVersion.SemanticVersion Version

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC TRC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("css")
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CLI" asp-action="Index">MVC TRC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CLI" asp-action="Index">CLI</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WASD" asp-action="Index">GUI</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            MVC TRC @Version.ToString() - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Applications/MVC/Views/Shared/_Robot.cshtml
@using ToyRobotChallenge.Library.Geometry
@using static ToyRobotChallenge.Library.AppSupport.Models.ToyRobotModel
@model MVCToyRobotChallenge.Models.ToyRobotModel

@if (this.Model != null)
{
    @switch (this.Model.State)
    {
        case RobotState.Waving:
            {
                <text>
                    <img class="robot" src="~/images/robot_front_wave.png" />
                </text>
            }
            break;

        case RobotState.Jumping:
            {
                <text>
                    <img class="robot" src="~/images/robot_front_jump.png" />
                </text>
            }
            break;

        case RobotState.Standing:
            {
                switch (this.Model.Vector.Dir)
                {
                    case Direction.North:
                        <text>
                            <img class="robot" src="~/images/robot_back.png" />
                        </text>
                        break;
                    case Direction.East:
                        <text>
                            <img class="robot" src="~/images/robot_right.png" />
                        </text>
                        break;
                    case Direction.South:
                        <text>
                            <img class="robot" src="~/images/robot_front.png" />
                        </text>
                        break;
                    case Direction.West:
                        <text>
                            <img class="robot" src="~/images/robot_left.png" />
                        </text>
                        break;
                    default:
                        break;
                }
            }
            break;

        default:
            break;
    }
}

@{
}

Applications/MVC/Views/Shared/_Tabletop.cshtml
@using MVCToyRobotChallenge.Models
@using static ToyRobotChallenge.Library.AppSupport.Models.ToyRobotModel
@model TabletopModel
<!-- build the table grid -->
<div class="container">
    @for (var y = this.Model.Rows - 1; y >= 0; y--)
    {
        <div class="row">
            @for (var x = 0; x < this.Model.Columns; x++)
            {
                <div class="col tabletopgridbox">
                    <span>(@x,@y)</span>

                    @if (true
                        && this.Model.RobotModel != null
                        && this.Model.RobotModel.State != RobotState.None
                        && this.Model.RobotModel.Vector != null
                        && this.Model.RobotModel.Vector.Position.X == x
                        && this.Model.RobotModel.Vector.Position.Y == y)
                    {
                        <span>
                            <partial name="_Robot" model="@this.Model.RobotModel" />
                        </span>
                    }
                </div>
            }
        </div>
    }
</div>

@{
}